### ISSUE TITLE
Faculty Module

### ISSUE THREAD

**Issue by RiyaadHossain** [RiyaadHossain/University-Management-Auth-Service#37]
## Task: Complete Faculty Module

 

- [x] Generate faculty utility function to create faculty incremental id.

   - Pattern: F-00001

- [x] Create `/create-faculty` route in `user.route.ts` file.

- [x]  Validate Create Faculty Request in router level.

- [x] Create Faculty controller and service in `user.controller.ts` & `user.service.ts`.

- [x] Create API End Points in `faculty.route.ts` given below (Do not forget to add it in `routes/index.ts` file):
   - `/api/v1/faculties` (GET) → Get all faculties, implement filtering and pagination, populate reference field.
   - `/api/v1/faculties/:id` (GET) → Get individual faculty by ID and populate reference field.
   - `/api/v1/faculties/:id` (PATCH) → Update faculty data dynamically.
   - `/api/v1/faculties/:id` (DELETE) → Delete individual faculty.

- [x]  Validate Update request using Zod schema.

- [x]  Create faculty controllers and services.

- [x]  Test APIs and Create Data.
